services:
  - type: web
    name: midea-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        fromService:
          type: web
          property: port
